feat: add function to fund tournament
onlydustxyz/starkonquest pull request #54
Opened 2022-05-25 12:45 UTC by ftupas

This PR is for issue https://github.com/onlydustxyz/starkonquest/issues/44.

The goal is to allow people to fund the tournament, in the form of ERC20 tokens. Upon inspection, it already had the getter function for the ERC20 token address and the value is only set in the constructor (not changeable). I've proceed and did the following:
- create `deposit_rewards` **external** function that
  transfers ERC20 tokens from caller to the tournament contract
- create `rewards_deposited` **event**
- add test for depositing rewards

2022-05-25 12:50 UTC, ftupas commented on contracts/tournament/library.cairo
> +        rewards_deposited.emit(caller_address, amount)
Entrypoint here. Calling `transferFrom` function of the ERC20 reward token address to transfer funds from the caller to the tournament contract

2022-05-25 12:50 UTC, ftupas commented on contracts/tournament/test_tournament.cairo
> +    %}
Deploying the ERC20 token here and saving the address in a local variable to pass it in the constructor later

2022-05-30 12:43 UTC, ofux requested changes
Great job!
I just added a comment in the test.

I think we will want to implement an escrow contract in the future, to be able to handle refunds for example, but this will be done in other issues. Your PR perfectly answers the need 👍

2022-05-30 12:43 UTC, ofux commented on contracts/tournament/test_tournament.cairo
> +    %{ expect_revert("TRANSACTION_FAILED", "ERC20: transfer amount exceeds allowance") %}
`expect_revert` is kind of a trap. Once it is called, any further revert is ignored until the end of the test, meaning everything you test after this is actually, well, not tested :)

I think there should be 2 tests because of this:
- one that expect the revert (and nothing more happens after this)
- another that goes til the end of the process

2022-05-30 13:09 UTC, ftupas commented on contracts/tournament/test_tournament.cairo
> +    %{ expect_revert("TRANSACTION_FAILED", "ERC20: transfer amount exceeds allowance") %}
I see that makes sense actually, I couldn't find `stop_expect_revert()` and just assumed that it only applies to the succeeding line 😅 good to know about this and thanks! I'' create 2 tests for this as you've mentioned

2022-05-30 20:04 UTC, ftupas commented on contracts/tournament/test_tournament.cairo
> +    alloc_locals
Took this opportunity to organize helper functions a little bit better for integration testing. This could be used for when contracts need to be deployed to test i.e. `deposit_rewards` and future `winner_withdraw` feature. Please let me know what you think 🙂

2022-05-31 16:29 UTC, ofux approved these changes
Great work! Clean and well tested code 👍 
Thanks you very much for this contribution

2022-05-31 20:58 UTC, ftupas commented on contracts/tournament/test_tournament.cairo
> +        assert_that.token_balances_are(
Thanks for the feedback and review as well! 🙏

2022-06-01 14:14 UTC, merged